media:
  input: src/content/imagess
  output: /imagess

content:
# PREMIÈRE COLLECTION : LES TABLEAUX
  - name: tableauxx
    label: Mes Tableaux
    type: collection
    path: src/content/tableauxx
    fields:
      - name: title
        label: Titre du tableau
        type: string
      - name: description
        label: Description
        type: rich-text
      - name: image
        label: Photo du tableau
        type: image
      - name: prix
        label: Prix (en €)
        type: number

# DEUXIÈME COLLECTION : LES ACTUALITÉS
  - name: articless
    label: Mes Actualités
    type: collection
    path: src/content/articless
    fields:
      - name: title
        label: Titre de l'article
        type: string
      - name: content
        label: Contenu
        type: rich-text